Gestion-Emploi/Controllers/AnneController.cs
using GestionEmploi.App_Start;
using GestionEmploi.Models;
using GestionEmploi.Services;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GestionEmploi.Controllers
{
    public class AnneController : Controller
    {


        public IDbContext db;
        public IDAO<Annee> dao;
        public AnneController(IDAO<Annee> dao, IDbContext db)
        {
            this.dao = dao;
            this.db = db;
        }
        // GET: Anne+
        public ActionResult Index()
        {

            List<Annee> liste = dao.getAll();
            ViewData["list"] = liste;
            // return Json(liste,JsonRequestBehavior.AllowGet);
            return View();
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteAnnee(int id)
        {
            Console.WriteLine(id);
            dao.delete(id);
            return RedirectToAction("Index");
        }

        public ActionResult Create()
        {

            return View("Create");
        }



        [HttpPost]
        public ActionResult AJouter_Annee(Annee an)
        {
            Debug.WriteLine(an);
            var j = dao.create(an);
            Debug.WriteLine(j);
            return RedirectToAction("Index");
        }

        
        
        public ActionResult EDIT(int id)
        {
            Annee annee = dao.getById(id);
            return View(annee);

        }

       

        [HttpPost]
        public ActionResult Update(Annee annee)
        {

       
                
                    var annn = dao.getById(annee.AnneeId);
                    annn.Libelle = annee.Libelle;
                    annn.DateDebut = annee.DateDebut;
                    annn.DateFin = annee.DateFin;
                    dao.update(annn);
                
      return RedirectToAction("Index");

    }
}
}

Gestion-Emploi/Views/Anne/AJouter_Annee.cshtml
@model IEnumerable<GestionEmploi.Models.Annee>
@{
    ViewBag.Title = "AJouter_Annee";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>AJouter_Annee</h2>




<div class="container">



    @Html.ActionLink("+ Add", "Create", null, null, new { @class = "btn btn-primary" })
   
    <br />
    <br />
    <div class="table-responsive">
        <table class="table text-center">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Libelle</th>
                    <th>Date de debut</th>
                    <th>Date de Fin</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>

                @foreach (var annee in ViewData["list"] as IEnumerable<GestionEmploi.Models.Annee>)
                {
                    <tr>
                        <td> @annee.AnneeId</td>
                        <td> @annee.Libelle</td>
                        <td>@annee.DateDebut</td>
                        <td>@annee.DateFin</td>

                        <td class="d-flex accordion-collapse ">
                            @using (Html.BeginForm("Delete", "Anne", new { id = annee.AnneeId, FormMethod.Post }))
                            {
                                @Html.AntiForgeryToken()

                                <input class="btn btn-danger" type="submit" value="delete" />
                            }

                            @using (Html.BeginForm("EDIT", "Anne", new { id = annee.AnneeId, FormMethod.Post }))
                            {
                                @Html.AntiForgeryToken()

                                <button class="btn btn-success" >UPDATE</button>
                            }
                            <button class="btn btn-info">Info</button>
                        </td>
                    </tr>




                }

            </tbody>
        </table>
    </div>

</div>

Gestion-Emploi/Views/Anne/Create.cshtml
@model GestionEmploi.Models.Annee

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />

@Styles.Render("~/Content/form.css")


@using (Html.BeginForm("AJouter_Annee", "Anne", FormMethod.Post))

{
@Html.ValidationSummary(true, "", new { @class = "text-danger" })
<div class="container">
    <div class="form-group">
        @if (Model != null && Model.AnneeId > 0)
            {
        @Html.HiddenFor(x => x.AnneeId)
            }
        <div class="container mt-5 mb-5">
            <div class="row d-flex align-items-center justify-content-center">
                <div class="col-md-6">
                    <div class="card px-5 py-5">
                        <span class="circle"><i class="fa fa-check"></i></span>
                        <h5 class="mt-3">Ajouter une Nouvelle Annee </h5>
                        <div class="form-input">
                            <i class="fa fa-user"></i>
                            @Html.TextBoxFor(x => x.Libelle, new { placeholder = "Libelle", @class = "form-control" })

                        </div>

                        <div class="form-group d-flex mb-2">

                            @Html.EditorFor(x => x.DateDebut, new { htmlAttributes = new { placeholder = "Date de début", @class = "form-control datepicker me-2 " } } )
                            @Html.ValidationMessageFor(x => x.DateDebut, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group d-flex">

                            @Html.EditorFor(x => x.DateFin, new
                       {
                           htmlAttributes = new
                           {
                               placeholder = "Date de Fin",
                               @class = "form-control datepicker me-2"
                               /*  @readonly ="true",value = Model.DateFin.ToString("YYYY-MM-DD")*/
                           }
                       })
                            @Html.ValidationMessageFor(x => x.DateFin, "", new { @class = "text-danger" })
                        </div>

                        <div> <input type="submit" value="Ajouter" class=" btn-success mt-4 signup" /> </div>
                    </div>

                </div>

            </div>
        </div>
    </div>
</div>



@*@section Scripts{
        @Scripts.Render("~/bundles/jqueryui")
        @Styles.Render("~/Content/cssjqryUi")

        <script type="text/javascript">
            $(document).ready(function () {
                $('input[type=datetime]').datepicker({
                    dateFormat: "dd/M/yy",
                    changeMonth: true,
                    changeYear: true,
                    yearRange: "-60:+0"
                });
            });
        </script>
    }*@



@section scripts{


    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>

    <script>

            $(function () {
                $(".datepicker").datepicker({

                    dateFormat: "yy/mm/dd",
                    changeMonth: true,
                    changeYear: true,
                    yearRange: "-10:+10",
                    minDate: new Date(2005, 0, 1),
                    maxDate: new Date(2022, 0, 1),
                    showOn: "both",
                    buttonText: "<i class='fa fa-calendar'></i>",






                });


            });



    </script>




}

























}

Gestion-Emploi/Views/Anne/EDIT.cshtml
@model GestionEmploi.Models.Annee
@{
    ViewBag.Title = "EDIT";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>EDIT</h2>

<link href="~/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />

@Styles.Render("~/Content/form.css")


@using (Html.BeginForm("Update", "Anne", FormMethod.Post))

{

@Html.ValidationSummary(true, "", new { @class = "text-danger" })
<div class="container">
    <div class="form-group">
        @if (Model != null && Model.AnneeId > 0)
            {
               @Html.HiddenFor(x => x.AnneeId)
            }
        <div class="container mt-5 mb-5">
            <div class="row d-flex align-items-center justify-content-center">
                <div class="col-md-6">
                    <div class="card px-5 py-5">
                        <span class="circle"><i class="fa fa-check"></i></span>
                        <h5 class="mt-3">Ajouter une Nouvelle Annee </h5>
                        <div class="form-input">
                            <i class="fa fa-user"></i>
                            @Html.TextBoxFor(x => x.Libelle, new { placeholder = "Libelle", @class = "form-control" })

                        </div>

                        <div class="form-group d-flex mb-2">

                            @Html.EditorFor(x => x.DateDebut, new { htmlAttributes = new { placeholder = "Date de début", @class = "form-control datepicker me-2 " } })
                            @Html.ValidationMessageFor(x => x.DateDebut, "", new { @class = "text-danger" })
                        </div>
                        <div class="form-group d-flex">

                            @Html.EditorFor(x => x.DateFin, new
                       {
                           htmlAttributes = new
                           {
                               placeholder = "Date de Fin",
                               @class = "form-control datepicker me-2"
                               /*  @readonly ="true",value = Model.DateFin.ToString("YYYY-MM-DD")*/
                           }
                       })
                            @Html.ValidationMessageFor(x => x.DateFin, "", new { @class = "text-danger" })
                        </div>

                        <div> <input type="submit" value="Ajouter" class=" btn-success mt-4 signup" /> </div>
                    </div>

                </div>

            </div>
        </div>
    </div>
</div>



@*@section Scripts{
        @Scripts.Render("~/bundles/jqueryui")
        @Styles.Render("~/Content/cssjqryUi")

        <script type="text/javascript">
            $(document).ready(function () {
                $('input[type=datetime]').datepicker({
                    dateFormat: "dd/M/yy",
                    changeMonth: true,
                    changeYear: true,
                    yearRange: "-60:+0"
                });
            });
        </script>
    }*@



@section scripts{


    <script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>

    <script>

            $(function () {
                $(".datepicker").datepicker({

                    dateFormat: "yy/mm/dd",
                    changeMonth: true,
                    changeYear: true,
                    yearRange: "-10:+10",
                    minDate: new Date(2005, 0, 1),
                    maxDate: new Date(2022, 0, 1),
                    showOn: "both",
                    buttonText: "<i class='fa fa-calendar'></i>",






                });


            });



    </script>




}

























}

Gestion-Emploi/Views/Anne/Index.cshtml
@model IEnumerable<GestionEmploi.Models.Annee>
@{
    ViewBag.Title = "AJouter_Annee";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>AJouter_Annee</h2>




<div class="container">



    @Html.ActionLink("+ Add", "Create", null, null, new { @class = "btn btn-primary" })
   
    <br />
    <br />
    <div class="table-responsive">
        <table class="table text-center">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Libelle</th>
                    <th>Date de debut</th>
                    <th>Date de Fin</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>

                @foreach (var annee in ViewData["list"] as IEnumerable<GestionEmploi.Models.Annee>)
                {
                    <tr>
                        <td> @annee.AnneeId</td>
                        <td> @annee.Libelle</td>
                        <td>@annee.DateDebut</td>
                        <td>@annee.DateFin</td>

                        <td class="d-flex accordion-collapse ">
                            @using (Html.BeginForm("Delete", "Anne", new { id = annee.AnneeId, FormMethod.Post }))
                            {
                                @Html.AntiForgeryToken()

                                <input class="btn btn-danger" type="submit" value="delete" />
                            }

                            @using (Html.BeginForm("EDIT", "Anne", new { id = annee.AnneeId, FormMethod.Post }))
                            {
                                @Html.AntiForgeryToken()

                                <button class="btn btn-success" >UPDATE</button>
                            }
                            <button class="btn btn-info">Info</button>
                        </td>
                    </tr>




                }

            </tbody>
        </table>
    </div>

</div>