Gestion-Emploi/Models/Professor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace GestionEmploi.Models
{
  public class Professor
  {
    [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
    public int ProfessorId { get; set; }
      [Required]
      public string FirstName { get; set; }
        [Required]
        public string LastName { get; set; }
        [Required]
        public string Email { get; set; }

    public virtual List<Cour> Cours { get; set; }


  }
}

Gestion-Emploi/Controllers/ProfessorController.cs
using GestionEmploi.Models;
using GestionEmploi.Services;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GestionEmploi.Controllers
{
    public class ProfessorController : Controller
    {

        IProfessorService dao;

        public ProfessorController(IProfessorService dao)
        {
            this.dao = dao;
        }

        
         public ActionResult AddProfessor(Professor professor)
        {
            if (professor != null)
            {
                return View(professor);
            }
            else
            {
                return View();
            }
           
        }
        [HttpPost]
        public ActionResult AddProfessorToBd(Professor professor)
        {
            dao.create(professor);         
            return RedirectToAction("ListProfessor");
        }


        public ActionResult Index()
        {
            List<Professor> professors = dao.getAll();
            ViewData["list"] = professors;
            return View();
        }
        public ActionResult Delete(int id)
        {
            dao.delete(id);
            return RedirectToAction("Index");
        }

        public ActionResult EditeProfessor(int id)
        {
            Professor professor = dao.getById(id);
            return View(professor);
        }

        [HttpPost]
        public ActionResult EditProfessorDb(Professor professor)
        {
            
                Professor profUpdate = dao.getById(professor.ProfessorId);
                profUpdate.Email = professor.Email;
                profUpdate.LastName = professor.LastName;
                profUpdate.FirstName = professor.FirstName;
                dao.update(profUpdate);
               
          
            return RedirectToAction("Index");
        }
    }
}

Gestion-Emploi/Views/Professor/AddProfessor.cshtml
@model GestionEmploi.Models.Professor
@{
    ViewBag.Title = "AddProfessor";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Styles.Render("~/Content/form.css")



@using (Html.BeginForm("AddProfessorToBd", "Professor", FormMethod.Post))
{
    <div class="container">
        <div class="form-group">
            <div class="container mt-5 mb-5">
                <div class="row d-flex align-items-center justify-content-center">
                    <div class="col-md-6">
                        <div class="card px-5 py-5">
                            <span class="circle"><i class="fa fa-check"></i></span>
                            <h5 class="mt-3">Ajouter une Professeur </h5>
                            <div class="form-input">
                                <label>Nom</label>
                                @Html.TextBoxFor(x => x.LastName, new { placeholder = "ecrire le nom", @class = "form-control" })
                                @Html.ValidationMessageFor(x => x.LastName, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-input">
                                <label>Prenom</label>
                                @Html.TextBoxFor(x => x.FirstName, new { placeholder = "ecrire le prenom", @class = "form-control" })
                                @Html.ValidationMessageFor(x => x.FirstName, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-input">
                                <label>Email</label>
                                @Html.TextBoxFor(x => x.Email, new { placeholder = "ecrire l'email", @class = "form-control" })
                                @Html.ValidationMessageFor(x => x.Email, "", new { @class = "text-danger" })
                            </div>
                            <div>
                                <input type="submit" value="Ajouter" class="btn btn-primary mt-4 signup" />
                            </div>
                        </div>

                    </div>

                </div>
            </div>
        </div>

    </div>
}

Gestion-Emploi/Views/Professor/EditeProfessor.cshtml
@model GestionEmploi.Models.Professor
@{
    ViewBag.Title = "EditeProfessor";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Styles.Render("~/Content/form.css")


@using (Html.BeginForm("EditProfessorDb", "Professor", FormMethod.Post))
{
    <div class="container">
        <div class="form-group">
            @if (Model != null && Model.ProfessorId > 0)
            {
                @Html.HiddenFor(x => x.ProfessorId)
            }
            <div class="container mt-5 mb-5">
                <div class="row d-flex align-items-center justify-content-center">
                    <div class="col-md-6">
                        <div class="card px-5 py-5">
                            <span class="circle"><i class="fa fa-check"></i></span>
                            <h5 class="mt-3">Modifier une Professeur </h5>
                            <div class="form-input">
                                <label>Nom</label>
                                @Html.TextBoxFor(x => x.LastName, new { placeholder = "ecrire le nom", @class = "form-control" })
                            </div>
                            <div class="form-input">
                                <label>Prenom</label>
                                @Html.TextBoxFor(x => x.FirstName, new { placeholder = "ecrire le prenom", @class = "form-control" })
                            </div>
                            <div class="form-input">
                                <label>Email</label>
                                @Html.TextBoxFor(x => x.Email, new { placeholder = "ecrire l'email", @class = "form-control" })
                            </div>
                            <div>
                                <input type="submit" value="Modifier" class="btn btn-primary mt-4 signup" />
                            </div>
                        </div>

                    </div>

                </div>
            </div>
        </div>

    </div>
}

Gestion-Emploi/Views/Professor/Index.cshtml
@model IEnumerable<GestionEmploi.Models.Professor>

@{
    ViewBag.Title = "ListProfessor";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Liste des Professeur</h2>
<div class="container">
    @Html.ActionLink("+ Add", "AddProfessor", null, null, new { @class = "btn btn-primary" })

    <br />
    <br />
    <div class="table-responsive">
        <table class="table text-center">
            <thead>
                <tr>
                    <th>Nom</th>
                    <th>Prenom</th>
                    <th>Email</th>
                    <th>Action</th>

                </tr>
            </thead>
            <tbody>


                @foreach (var prof in ViewData["list"] as IEnumerable<GestionEmploi.Models.Professor>)
                {
                    <tr>

                        <td>@prof.LastName</td>
                        <td>@prof.FirstName</td>
                        <td>@prof.Email</td>

                        <td>
                            <a href="@Url.Action("Delete",new { id = prof.ProfessorId})" class="btn btn-danger">Delete</a>


                            <a href="@Url.Action("EditeProfessor",new { id = prof.ProfessorId})" class="btn btn-success">Updtae</a>
                        </td>

                    </tr>




                }


            </tbody>
        </table>
    </div>
</div>

Gestion-Emploi/Views/Professor/ListProfessor.cshtml
@model IEnumerable<GestionEmploi.Models.Professor>

@{
    ViewBag.Title = "ListProfessor";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Liste des Professeur</h2>
<div class="container">
    @Html.ActionLink("+ Add", "AddProfessor", null, null, new { @class = "btn btn-primary" })

    <br />
    <br />
    <div class="table-responsive">
        <table class="table text-center">
            <thead>
                <tr>
                    <th>Nom</th>
                    <th>Prenom</th>
                    <th>Email</th>
                    <th>Action</th>

                </tr>
            </thead>
            <tbody>


                @foreach (var prof in ViewData["list"] as IEnumerable<GestionEmploi.Models.Professor>)
                {
                    <tr>

                        <td>@prof.LastName</td>
                        <td>@prof.FirstName</td>
                        <td>@prof.Email</td>

                        <td>
                            <a href="@Url.Action("Delete",new { id = prof.ProfessorId})" class="btn btn-danger">Delete</a>


                            <a href="@Url.Action("EditeProfessor",new { id = prof.ProfessorId})" class="btn btn-success">Updtae</a>
                        </td>

                    </tr>




                }


            </tbody>
        </table>
    </div>
</div>