Gestion-Emploi/Models/Cour.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace GestionEmploi.Models
{
  public class Cour
  {
    [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]

    public int CourId { get; set; }

        [Required]
        public string Libelle { get; set; }
        [Required]
        public int ResponsableId { get; set; }

        [ForeignKey("ResponsableId")]
        public virtual Professor Responsable { get; set; }
        [Required]
        [ForeignKey("Niveau")]
    public int NiveauId { get; set; }
    public virtual Niveau Niveau { get; set; }

    public virtual List<DetailEmplois> DetailEmplois { get; set; }


  }
}

Gestion-Emploi/Controllers/CourController.cs
using GestionEmploi.App_Start;
using GestionEmploi.Models;
using GestionEmploi.Services;
using System.Collections.Generic;
using System.Web.Mvc;

namespace GestionEmploi.Controllers
{
    public class CourController : Controller
    {
        GestionEmploisDbContext db = new GestionEmploisDbContext();
        ICourService dao;
        IProfessorService daoProf;
        

        public CourController(ICourService dao)
        {
            this.dao = dao;
        }


        public ActionResult Index()
        {
            List<Cour> cours = dao.getAll();
            ViewData["list"] = cours;
            return View();
        }


        public ActionResult AddCour()
        {
            ViewBag.profs = new SelectList(db.Professors, "ProfessorId","LastName");
            ViewBag.niveaux = new SelectList(db.Niveaux, "NiveauId", "libelle");
            return View();
        }

        [HttpPost]
        public ActionResult AddCour(Cour cour)
        {
            dao.create(cour);
            return RedirectToAction("Index");
    }

        public ActionResult Delete(int id)
        {
            dao.delete(id);
            return RedirectToAction("Index");
        }

        public ActionResult EditeCour(int id)
        {
            Cour cour = dao.getById(id);
            return View(cour);
        }
    }
}

Gestion-Emploi/Views/Cour/AddCour.cshtml
@model GestionEmploi.Models.Cour
@{
    ViewBag.Title = "AddCour";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@Styles.Render("~/Content/form.css")


@using (Html.BeginForm("AddCour", "Cour", FormMethod.Post))
{
    <div class="container">
        <div class="form-group">
            @if (Model != null && Model.CourId > 0)
            {
                @Html.HiddenFor(x => x.CourId)
            }
            <div class="container mt-5 mb-5">
                <div class="row d-flex align-items-center justify-content-center">
                    <div class="col-md-6">
                        <div class="card px-5 py-5">
                            <span class="circle"><i class="fa fa-check"></i></span>
                            <h5 class="mt-3">Ajouter un Cour </h5>
                            <div class="form-input">
                                <i class="fa fa-user"></i>
                                @Html.TextBoxFor(x => x.Libelle, new { placeholder = "Libelle", @class = "form-control" })
                                @Html.ValidationMessageFor(x => x.Libelle, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-input">
                                <i class="fa fa-user"></i>
                                @Html.DropDownListFor(x => x.ResponsableId, ViewBag.profs as SelectList, "Selectioner le responsable", new { @class = "form-control" })
                                @Html.ValidationMessageFor(x => x.ResponsableId, "", new { @class = "text-danger" })
                            </div>
                            <div class="form-input">
                                <i class="fa fa-user"></i>
                                @Html.DropDownListFor(x => x.NiveauId, ViewBag.niveaux as SelectList, "Selectioner le niveaux", new { @class = "form-control" })
                                @Html.ValidationMessageFor(x => x.NiveauId, "", new { @class = "text-danger" })
                            </div>
                            <div> <input type="submit" value="Ajouter" class="btn btn-primary mt-4 signup" /> </div>
                        </div>

                    </div>

                </div>
            </div>
        </div>
    </div>







}

Gestion-Emploi/Views/Cour/EditeCour.cshtml
@model GestionEmploi.Models.Cour
@{
    ViewBag.Title = "EditeCour";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Styles.Render("~/Content/form.css")


@using (Html.BeginForm("EditCour", "Cour", FormMethod.Post))
{
    <div class="container">
        <div class="form-group">
            @if (Model != null && Model.CourId > 0)
            {
                @Html.HiddenFor(x => x.CourId)
            }
            <div class="container mt-5 mb-5">
                <div class="row d-flex align-items-center justify-content-center">
                    <div class="col-md-6">
                        <div class="card px-5 py-5">
                            <span class="circle"><i class="fa fa-check"></i></span>
                            <h5 class="mt-3">Modifier un Cour </h5>
                            <div class="form-input">
                                <i class="fa fa-user"></i>
                                @Html.TextBoxFor(x => x.Libelle, new { placeholder = "Libelle", @class = "form-control" })

                            </div>
                            <div class="form-input">
                                <i class="fa fa-user"></i>
                                @Html.DropDownListFor(x => x.ResponsableId, ViewBag.profs as SelectList, "Selectioner le responsable", new { @class = "form-control" })
                            </div>
                            <div class="form-input">
                                <i class="fa fa-user"></i>
                                @Html.DropDownListFor(x => x.NiveauId, ViewBag.niveaux as SelectList, "Selectioner le niveaux", new { @class = "form-control" })
                            </div>
                            <div> <input type="submit" value="Modifier" class="btn btn-primary mt-4 signup" /> </div>
                        </div>

                    </div>

                </div>
            </div>
        </div>
    </div>







}

Gestion-Emploi/Views/Cour/Index.cshtml
@model IEnumerable<GestionEmploi.Models.Cour>

@{
    ViewBag.Title = "ListCour";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Liste des Professeur</h2>
<div class="container">
    @Html.ActionLink("+ Add", "AddCour", null, null, new { @class = "btn btn-primary" })

    <br />
    <br />
    <div class="table-responsive">
        <table class="table text-center">
            <thead>
                <tr>
                    <th>Libelle</th>
                    <th>Responsable</th>
                    <th>Niveau</th>
                    <th>Action</th>

                </tr>
            </thead>
            <tbody>


                @foreach (var cour in ViewData["list"] as IEnumerable<GestionEmploi.Models.Cour>)
                {
                    <tr>

                        <td>@cour.Libelle</td>
                        <td>@cour.Responsable.FirstName @cour.Responsable.LastName</td>
                        <td>@cour.Niveau.libelle</td>

                        <td>
                            <a href="@Url.Action("Delete",new { id = cour.CourId})" class="btn btn-danger">Delete</a>


                            <a href="@Url.Action("EditeCour",new { id = cour.CourId})" class="btn btn-success">Updtae</a>
                        </td>

                    </tr>

                }
            </tbody>
        </table>
    </div>
</div>

Gestion-Emploi/Views/Cour/ListCour.cshtml
@model IEnumerable<GestionEmploi.Models.Cour>

@{
    ViewBag.Title = "ListCour";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Liste des Professeur</h2>
<div class="container">
    @Html.ActionLink("+ Add", "AddCour", null, null, new { @class = "btn btn-primary" })

    <br />
    <br />
    <div class="table-responsive">
        <table class="table text-center">
            <thead>
                <tr>
                    <th>Libelle</th>
                    <th>Responsable</th>
                    <th>Niveau</th>
                    <th>Action</th>

                </tr>
            </thead>
            <tbody>


                @foreach (var cour in ViewData["list"] as IEnumerable<GestionEmploi.Models.Cour>)
                {
                    <tr>

                        <td>@cour.Libelle</td>
                        <td>@cour.Responsable.FirstName @cour.Responsable.LastName</td>
                        <td>@cour.Niveau.libelle</td>

                        <td>
                            <a href="@Url.Action("DeleteCour",new { id = cour.CourId})" class="btn btn-danger">Delete</a>


                            <a href="@Url.Action("EditeCour",new { id = cour.CourId})" class="btn btn-success">Updtae</a>
                        </td>

                    </tr>

                }
            </tbody>
        </table>
    </div>
</div>