Gestion-Emploi/Models/Filiere.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace GestionEmploi.Models
{
  public class Filiere
  {
    [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
    [Key]
    public int FiliereId { get; set; }
    [Required]
    public string Libelle { get; set; }

  }
}

Gestion-Emploi/Controllers/FiliereController.cs
using GestionEmploi.App_Start;
using GestionEmploi.Models;
using GestionEmploi.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GestionEmploi.Controllers
{
    public class FiliereController : Controller
    {
        GestionEmploisDbContext db = new GestionEmploisDbContext();

        public IDAO<Filiere> dao;
        public FiliereController(IDAO<Filiere> dao)
        {
            this.dao = dao;
        }
        
        // GET: Filiere
        public ActionResult Index()
        {
             List<Filiere> liste = dao.getAll();
            ViewData["list"] = liste;
            return View();
        }
    
       
        public ActionResult Delete(int id)
        {
            dao.delete(id);
            return RedirectToAction("Index");
        }
        public ActionResult Edit(int id)
        {
            Filiere filiere = dao.getById(id);
            return View(filiere);

        }

        public ActionResult Create()
        {   
            return View("Create");
        }
       [HttpPost]
      public ActionResult AddFiliere(Filiere filiere)
        {
            if (ModelState.IsValid)
            {
                Filiere f = new Filiere
                {
                    Libelle = filiere.Libelle
                };
                dao.create(f);
            }
           
            return RedirectToAction("Index");

        }
        [HttpPost]
        public ActionResult Update(Filiere filiere)
        {
           
            Filiere filiere1 = dao.getById(filiere.FiliereId);
            filiere1.Libelle = filiere.Libelle;
            dao.update(filiere1);
            return RedirectToAction("Index");

        }

        
    }
}

Gestion-Emploi/Views/Filiere/Create.cshtml
@model GestionEmploi.Models.Filiere
@{
    ViewBag.Title = "Local";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Styles.Render("~/Content/form.css")



@using (Html.BeginForm("AddFiliere", "Filiere", FormMethod.Post))
{
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="container">
        <div class="form-group">
            @if (Model != null && Model.FiliereId > 0)
            {
                @Html.HiddenFor(x => x.FiliereId)
            }
            <div class="container mt-5 mb-5">
                <div class="row d-flex align-items-center justify-content-center">
                    <div class="col-md-6">
                        <div class="card px-5 py-5">
                            <span class="circle"><i class="fa fa-check"></i></span>
                            <h5 class="mt-3">Ajouter une Filiere </h5>
                            <div class="form-input">
                                <i class="fa fa-user"></i>
                                @Html.TextBoxFor(x => x.Libelle, new { placeholder = "Libelle", @class = "form-control" })
                                @Html.ValidationMessageFor(x => x.Libelle, "", new { @class = "text-danger" })

                            </div>
                            <div> <input type="submit" value="Ajouter" class="btn btn-primary mt-4 signup" /> </div>
                        </div>

                    </div>

                </div>
            </div>
        </div>
    </div>







}

Gestion-Emploi/Views/Filiere/Edit.cshtml
@model GestionEmploi.Models.Filiere
@{
    ViewBag.Title = "Local";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@Styles.Render("~/Content/form.css")


@using (Html.BeginForm("Update", "Filiere", FormMethod.Post))
{
    <div class="container">
        <div class="form-group">
            @if (Model != null && Model.FiliereId > 0)
            {
                @Html.HiddenFor(x => x.FiliereId)
            }
            <div class="container mt-5 mb-5">
                <div class="row d-flex align-items-center justify-content-center">
                    <div class="col-md-6">
                        <div class="card px-5 py-5">
                            <span class="circle"><i class="fa fa-check"></i></span>
                            <h5 class="mt-3">Edit  <b>Filiere</b> </h5>
                            <div class="form-input">
                                <i class="fa fa-user"></i>
                                @Html.TextBoxFor(x => x.Libelle, new { placeholder = "Libelle", @class = "form-control" })
                                @Html.ValidationMessageFor(x => x.Libelle, "", new { @class = "text-danger" })
                            </div>
                            <div> <input type="submit" value="update" class="btn btn-primary mt-4 signup" /> </div>
                        </div>

                    </div>

                </div>
            </div>
        </div>
    </div>







}

Gestion-Emploi/Views/Filiere/Filiere.cshtml
@model IEnumerable<GestionEmploi.Models.Filiere>

@Styles.Render("~/Content/Filiere.css")

<div class="container">
    @Html.ActionLink("+ Add", "Create",null,null, new { @class = "btn btn-primary" })
  
    <br />
    <br />
    <div class="table-responsive">
        <table class="table text-center">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Libelle</th>
                    <th>Action</th>

                </tr>
            </thead>
            <tbody>


                @foreach (var filier in ViewData["list"] as IEnumerable<GestionEmploi.Models.Filiere>)
                {
                    <tr>

                        <td> @filier.FiliereId</td>
                        <td>@filier.Libelle</td>

                        <td>
                            <a href="@Url.Action("Delete",new { id = filier.FiliereId})" class="btn btn-danger">Delete</a>
                            <a href="@Url.Action("Edit",new { id = filier.FiliereId})" class="btn btn-success">Edit</a>
                        
                        </td>

                    </tr>




                }


            </tbody>
        </table>

       </div>

Gestion-Emploi/Views/Filiere/Index.cshtml
@model IEnumerable<GestionEmploi.Models.Filiere>

@Styles.Render("~/Content/Filiere.css")

<div class="container">
    @Html.ActionLink("+ Add", "Create",null,null, new { @class = "btn btn-primary" })
  
    <br />
    <br />
    <div class="table-responsive">
        <table class="table text-center">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Libelle</th>
                    <th>Action</th>

                </tr>
            </thead>
            <tbody>


                @foreach (var filier in ViewData["list"] as IEnumerable<GestionEmploi.Models.Filiere>)
                {
                    <tr>

                        <td> @filier.FiliereId</td>
                        <td>@filier.Libelle</td>

                        <td>
                            <a href="@Url.Action("Delete",new { id = filier.FiliereId})" class="btn btn-danger">Delete</a>
                            <a href="@Url.Action("Edit",new { id = filier.FiliereId})" class="btn btn-success">Edit</a>
                        
                        </td>

                    </tr>




                }


            </tbody>
        </table>

       </div>